pipeline {
    agent any

    environment {
        TF_CLI_ARGS = "-input=false"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/youniverse-tech/jenkins-pipeline-demo.git'
            }
        }

        stage('Initialize Terraform') {
            steps {
                script {
                    bat 'terraform init'
                }
            }
        }

        stage('Validate Terraform Configuration') {
            steps {
                script {
                    bat 'terraform validate'
                }
            }
        }

        stage('Plan Terraform Changes') {
            steps {
                script {
                    bat 'terraform plan -out=tfplan'
                }
            }
        }

        stage('Apply Terraform Changes') {
            steps {
                script {
                    bat 'terraform apply -auto-approve tfplan'
                }
            }
        }

        stage('Destroy Infrastructure (Optional)') {
            when {
                expression { return false }  // Set to true if you want auto destroy
            }
            steps {
                script {
                    bat 'terraform destroy -auto-approve'
                }
            }
        }
    }
}
